# permissions for end users to view adds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: add-viewer-role
rules:
- apiGroups:
  - math.example.com
  resources:
  - adds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - math.example.com
  resources:
  - adds/status
  verbs:
  - get
